package main;
// Generated 15/11/2006 17:05:00 by Hibernate Tools 3.1.0.beta4

import java.util.Date;


/**
 * Recibo generated by hbm2java
 */

public class Recibo  implements java.io.Serializable {


    // Fields    

     private int idRecibo;
     private Socio socio;
     private Liquidacion liquidacion;
     private int numeroRecibo;
     private float valor;
     private boolean devuelto;


    // Constructors

    /** default constructor */
    public Recibo() {
    }

    
    /** full constructor */
    public Recibo(int idRecibo, Socio socio, Liquidacion liquidacion, int numeroRecibo, float valor, boolean devuelto) {
        this.idRecibo = idRecibo;
        this.socio = socio;
        this.liquidacion = liquidacion;
        this.numeroRecibo = numeroRecibo;
        this.valor = valor;
        this.devuelto = devuelto;
    }
    

   
    // Property accessors

    public int getIdRecibo() {
        return this.idRecibo;
    }
    
    public void setIdRecibo(int idRecibo) {
        this.idRecibo = idRecibo;
    }

    public Socio getSocio() {
        return this.socio;
    }
    
    public void setSocio(Socio socio) {
        this.socio = socio;
    }

    public Liquidacion getLiquidacion() {
        return this.liquidacion;
    }
    
    public void setLiquidacion(Liquidacion liquidacion) {
        this.liquidacion = liquidacion;
    }

    public int getNumeroRecibo() {
        return this.numeroRecibo;
    }
    
    public void setNumeroRecibo(int numeroRecibo) {
        this.numeroRecibo = numeroRecibo;
    }

    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }

    public boolean isDevuelto() {
        return this.devuelto;
    }
    
    public void setDevuelto(boolean devuelto) {
        this.devuelto = devuelto;
    }
   








}
