package main;
// Generated 15/11/2006 17:05:00 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * Zona generated by hbm2java
 */

public class Zona  implements java.io.Serializable {


    // Fields    

     private int idZona;
     private Cobrador cobrador;
     private Set socios = new HashSet(0);


    // Constructors

    /** default constructor */
    public Zona() {
    }

	/** minimal constructor */
    public Zona(int idZona, Cobrador cobrador) {
        this.idZona = idZona;
        this.cobrador = cobrador;
    }
    
    /** full constructor */
    public Zona(int idZona, Cobrador cobrador, Set socios) {
        this.idZona = idZona;
        this.cobrador = cobrador;
        this.socios = socios;
    }
    

   
    // Property accessors

    public int getIdZona() {
        return this.idZona;
    }
    
    public Integer getIdZonaI() {
        return new Integer(this.idZona);
    }
    
    public void setIdZona(int idZona) {
        this.idZona = idZona;
    }

    public Cobrador getCobrador() {
        return this.cobrador;
    }
    
    public void setCobrador(Cobrador cobrador) {
        this.cobrador = cobrador;
    }

    public Set getSocios() {
        return this.socios;
    }
    
    public void setSocios(Set socios) {
        this.socios = socios;
    }
   
    public String toString(){
    	return this.getIdZonaI().toString();
    }


}
