package main;
// Generated 15/11/2006 17:05:00 by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * Categoria generated by hbm2java
 */

public class Categoria  implements java.io.Serializable {

	public static final int FAMILIAR = 1;
	public static final int MENOR = 2;
	public static final int CADETE = 3;
	public static final int MAYOR = 4;	
	public static final int VITALICIO = 5;

    // Fields    

     private int idCategoria;
     private float cuota;
     private String nombre;
     private int edadMin;
     private int edadMax;
     private String cuotaStr;
//     private Set socios = new HashSet(0);


    // Constructors

	/** default constructor */
    public Categoria() {
    }

	/** minimal constructor */
    public Categoria(int idCategoria, float cuota, String nombre, int edadMin, int edadMax, String cuotaStr) {
        this.idCategoria = idCategoria;
        this.cuota = cuota;
        this.nombre = nombre;
        this.edadMin = edadMin;
        this.edadMax = edadMax;
        this.cuotaStr = cuotaStr;
    }
  
//  ** full constructor *//*
    /*  
    *
    public Categoria(int idCategoria, float cuota, String nombre, int edadMin, int edadMax, String cuotaStr, Set socios) {
        this.idCategoria = idCategoria;
        this.cuota = cuota;
        this.nombre = nombre;
        this.edadMin = edadMin;
        this.edadMax = edadMax;
        this.socios = socios;
        this.cuotaStr = cuotaStr;
    }*/
    

   
    // Property accessors

    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }

    public float getCuota() {
        return this.cuota;
    }
    
    public void setCuota(float cuota) {
        this.cuota = cuota;
    }

    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getEdadMin() {
        return this.edadMin;
    }
    
    public void setEdadMin(int edadMin) {
        this.edadMin = edadMin;
    }

    public int getEdadMax() {
        return this.edadMax;
    }
    
    public void setEdadMax(int edadMax) {
        this.edadMax = edadMax;
    }

  /*  public Set getSocios() {
        return this.socios;
    }
    
    public void setSocios(Set socios) {
        this.socios = socios;
    }*/
    
    public String toString(){
    	return this.nombre;
    }
   
    public String getCuotaStr() {
		return cuotaStr;
	}

	public void setCuotaStr(String cuotaStr) {
		this.cuotaStr = cuotaStr;
	}








}
