/**
 * FrmAltaSocio.java
 *
 * Created on 14 de noviembre de 2006, 17:38
 */

package guiClub;

import java.awt.event.ActionEvent;
import java.util.Date;
import java.util.List;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

import main.AdministradorDeCategorias;
import main.AdministradorDeSocios;
import main.AdministradorDeZonas;
import main.Categoria;
import main.Zona;
import utils.*;
/**
 *
 * @author  
 */
public class FrmAltaSocio extends JDialog {
    
    
	/** Creates new form FrmAltaSocio */
    public FrmAltaSocio(FrmGestionSocios ventana) {
    	ventanaPadre = ventana;
    	initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private void initComponents() {
        panelAltaSocio = new javax.swing.JPanel();
        apellido = new javax.swing.JTextField();
        labelApellido = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelTipoDocumento = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        labelNumero = new javax.swing.JLabel();
        tipoDocumento = new javax.swing.JComboBox();
        labelFechaNacimiento = new javax.swing.JLabel();
        labelEdadAfiliacion = new javax.swing.JLabel();
        diaNacimiento = new javax.swing.JComboBox();
        mesNacimiento = new javax.swing.JComboBox();
        anioNacimiento = new javax.swing.JComboBox();
        labelBarra1 = new javax.swing.JLabel();
        labelBarra2 = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        categoria = new javax.swing.JComboBox();
        edadAfiliacion = new javax.swing.JTextField();
        labelZona = new javax.swing.JLabel();
        zona = new javax.swing.JComboBox();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        getContentPane().setLayout(new AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setTitle("Alta socio");
        setResizable(false);
        panelAltaSocio.setLayout(new AbsoluteLayout());

        panelAltaSocio.add(apellido, new AbsoluteConstraints(80, 50, 310, -1));

        labelApellido.setText("Apellido: ");
        panelAltaSocio.add(labelApellido, new AbsoluteConstraints(30, 50, -1, -1));

        labelNombre.setText("Nombre: ");
        panelAltaSocio.add(labelNombre, new AbsoluteConstraints(30, 90, -1, -1));

        labelTipoDocumento.setText("Tipo documento: ");
        panelAltaSocio.add(labelTipoDocumento, new AbsoluteConstraints(30, 130, -1, -1));

        panelAltaSocio.add(nombre, new AbsoluteConstraints(80, 90, 310, -1));

        panelAltaSocio.add(numero, new AbsoluteConstraints(270, 130, 100, -1));

        labelNumero.setText("N\u00famero: ");
        panelAltaSocio.add(labelNumero, new AbsoluteConstraints(220, 130, -1, -1));

        tipoDocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DNI", "LC", "LE", "EXT" }));
        panelAltaSocio.add(tipoDocumento, new AbsoluteConstraints(120, 130, 70, 20));

        labelFechaNacimiento.setText("Fecha nacimiento: ");
        panelAltaSocio.add(labelFechaNacimiento, new AbsoluteConstraints(30, 170, -1, -1));

        labelEdadAfiliacion.setText("Edad afiliciaci\u00f3n: ");
        panelAltaSocio.add(labelEdadAfiliacion, new AbsoluteConstraints(30, 210, -1, -1));

        diaNacimiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        
        panelAltaSocio.add(diaNacimiento, new AbsoluteConstraints(130, 170, 50, 20));

        mesNacimiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        panelAltaSocio.add(mesNacimiento, new AbsoluteConstraints(200, 170, 80, 20));

        Vector anios = new Vector();
        Date d = new Date(System.currentTimeMillis());
        int anio = d.getYear()+1900;
        
        for (int i=1900; i<=anio; i++){
        	anios.addElement(new Integer(i));
        	
        }
        
        anioNacimiento.setModel(new DefaultComboBoxModel(anios));
        panelAltaSocio.add(anioNacimiento, new AbsoluteConstraints(300, 170, 70, 20));

        labelBarra1.setText("/");
        panelAltaSocio.add(labelBarra1, new AbsoluteConstraints(190, 170, -1, -1));

        labelBarra2.setText("/");
        panelAltaSocio.add(labelBarra2, new AbsoluteConstraints(290, 170, -1, -1));

        labelCategoria.setText("Categor\u00eda: ");
        panelAltaSocio.add(labelCategoria, new AbsoluteConstraints(30, 250, -1, -1));

        //categoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Menor", "Cadete", "Mayor", "Vitalicio" }));
        List categorias = AdministradorDeCategorias.getCategorias();
        categorias.remove(AdministradorDeCategorias.getCategoriaFamiliar());
        categoria.setModel(new DefaultComboBoxModel(categorias.toArray()));
        panelAltaSocio.add(categoria, new AbsoluteConstraints(100, 250, 270, 20));

        panelAltaSocio.add(edadAfiliacion, new AbsoluteConstraints(130, 210, 40, -1));

        labelZona.setText("Zona: ");
        panelAltaSocio.add(labelZona, new AbsoluteConstraints(30, 290, -1, -1));

        zona.setModel(new DefaultComboBoxModel(AdministradorDeZonas.getZonas().toArray()));
        

        panelAltaSocio.add(zona, new AbsoluteConstraints(100, 290, 80, 20));

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        panelAltaSocio.add(aceptar, new AbsoluteConstraints(110, 350, -1, -1));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        panelAltaSocio.add(cancelar, new AbsoluteConstraints(240, 350, -1, -1));

        getContentPane().add(panelAltaSocio, new AbsoluteConstraints(10, 10, 430, 400));

        pack();
    }
    

    protected void cancelarActionPerformed(ActionEvent evt) {
		dispose();		
	}

	private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {

		try{
 
			edadAfiliacion.setText(edadAfiliacion.getText().trim());
			numero.setText(numero.getText().trim());
    		Validador.validateApellido(apellido.getText());
    		Validador.validateNombre(nombre.getText());
    		Validador.validateDocumento((String)tipoDocumento.getSelectedItem(),numero.getText());
    		Validador.validateEdadAfiliacion(edadAfiliacion.getText());
    		Validador.validateFechaNacimiento(diaNacimiento.getSelectedIndex()+1, mesNacimiento.getSelectedIndex(),
    										((Integer)anioNacimiento.getSelectedItem()).intValue(),
    										Integer.valueOf(edadAfiliacion.getText()).intValue());
    		Validador.validateCategoria(((Categoria)categoria.getSelectedItem()).getIdCategoria(), false, diaNacimiento.getSelectedIndex()+1,
    				mesNacimiento.getSelectedIndex(),((Integer)anioNacimiento.getSelectedItem()).intValue());
    	
    		Date d = new Date(((Integer)anioNacimiento.getSelectedItem()).intValue()-1900,
    				mesNacimiento.getSelectedIndex(),
    				diaNacimiento.getSelectedIndex()+1 );
    		
    		AdministradorDeSocios.CrearSocio(((Zona)zona.getSelectedItem()).getIdZona(),
    				((Categoria)categoria.getSelectedItem()).getIdCategoria(),nombre.getText(), 
    				apellido.getText(), (String)tipoDocumento.getSelectedItem(),
    				Long.valueOf(numero.getText()).longValue(),d,Integer.valueOf(edadAfiliacion.getText()).intValue());
    		
    		ventanaPadre.cargarDatos();
			dispose();
    		
    	} catch (ValidadorException e){
    		JOptionPane.showMessageDialog(this,e.getMensaje(),"Error",JOptionPane.WARNING_MESSAGE);
    	} catch (Exception e){
    		JOptionPane.showMessageDialog(this,e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
    	}
		
		
    }

   
    
    // Variables declaration 
    private javax.swing.JButton aceptar;
    private javax.swing.JComboBox anioNacimiento;
    private javax.swing.JTextField apellido;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox categoria;
    private javax.swing.JComboBox diaNacimiento;
    private javax.swing.JTextField edadAfiliacion;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelBarra1;
    private javax.swing.JLabel labelBarra2;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelEdadAfiliacion;
    private javax.swing.JLabel labelFechaNacimiento;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelTipoDocumento;
    private javax.swing.JLabel labelZona;
    private javax.swing.JComboBox mesNacimiento;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField numero;
    private javax.swing.JPanel panelAltaSocio;
    private javax.swing.JComboBox tipoDocumento;
    private javax.swing.JComboBox zona;
    private FrmGestionSocios ventanaPadre;
    // End of variables declaration
    
}
