/**
 * FrmGestionClub.java
 *
 * Created on 15 de noviembre de 2006, 15:20
 */

package guiClub;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.Toolkit;

/**
 *
 * @author  
 */
public class FrmGestionClub extends javax.swing.JFrame {
    
    /** Creates new form FrmGestionClub */
    public FrmGestionClub() {
        initComponents();
        center();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setLayout(new AbsoluteLayout());

        jLabel1.setText("Sistema de Gesti\u00f3n de club");
        jPanel1.add(jLabel1, new AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel1, new AbsoluteConstraints(140, 90, 260, 210));

        pack();
    }
   
	 /**
     * Centers the frame on the screen.
     *

     * This centering service is more or less in {@link UiUtil}; this duplication 
     * is justified only because the use of {@link UiUtil} would entail more 
     * class loading, which is not desirable for a splash screen.
     */
     private void center(){
       Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
       Rectangle frame = getBounds();
       setLocation((screen.width - frame.width)/2, (screen.height - frame.height)/2);
     }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestionClub().setVisible(true);
            }
        });
    }
    
    // Variables declaration 
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
    
}
