/**
 * FrmGestionClub.java
 *
 * Created on 15 de noviembre de 2006, 15:20
 */

package guiClub;

/**
 *
 * @author  
 */
public class FrmGestionClub extends javax.swing.JFrame {
    
    /** Creates new form FrmGestionClub */
    public FrmGestionClub() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
  
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jPanel1.setLayout(new AbsoluteLayout());

        jLabel1.setText("Sistema de Gesti\u00f3n de club");
        jPanel1.add(jLabel1, new AbsoluteConstraints(40, 30, -1, -1));

        getContentPane().add(jPanel1, new AbsoluteConstraints(140, 90, 260, 210));

        pack();
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestionClub().setVisible(true);
            }
        });
    }
    
    // Variables declaration 
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
    
}
